/*******************************************************************************
 * Copyright (c) 2020 Lablicate GmbH.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * SPDX-License-Identifier: EPL-1.0
 * 
 * Contributors:
 * generated by xjc compiler
 *******************************************************************************/
package org.eclipse.chemclipse.converter.methods.xml.v1;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Entry complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="settings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entry" type="{https://github.com/eclipse/chemclipse/processmethods/v1}Entry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="processor" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datacategories" use="required" type="{https://github.com/eclipse/chemclipse/processmethods/v1}DataCategoryList" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="readonly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", namespace = "https://github.com/eclipse/chemclipse/processmethods/v1", propOrder = {"settings", "entry"})
public class Entry {

	@XmlElement(namespace = "https://github.com/eclipse/chemclipse/processmethods/v1", required = true)
	protected String settings;
	@XmlElement(namespace = "https://github.com/eclipse/chemclipse/processmethods/v1")
	protected List<Entry> entry;
	@XmlAttribute(name = "processor", required = true)
	protected String processor;
	@XmlAttribute(name = "datacategories", required = true)
	protected List<String> datacategories;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "description")
	protected String description;
	@XmlAttribute(name = "readonly")
	protected Boolean readonly;

	/**
	 * Gets the value of the settings property.
	 * 
	 * @return
	 * 		possible object is
	 *         {@link String }
	 * 
	 */
	public String getSettings() {

		return settings;
	}

	/**
	 * Sets the value of the settings property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 * 
	 */
	public void setSettings(String value) {

		this.settings = value;
	}

	/**
	 * Gets the value of the entry property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the entry property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getEntry().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Entry }
	 * 
	 * 
	 */
	public List<Entry> getEntry() {

		if(entry == null) {
			entry = new ArrayList<Entry>();
		}
		return this.entry;
	}

	/**
	 * Gets the value of the processor property.
	 * 
	 * @return
	 * 		possible object is
	 *         {@link String }
	 * 
	 */
	public String getProcessor() {

		return processor;
	}

	/**
	 * Sets the value of the processor property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 * 
	 */
	public void setProcessor(String value) {

		this.processor = value;
	}

	/**
	 * Gets the value of the datacategories property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the datacategories property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getDatacategories().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link String }
	 * 
	 * 
	 */
	public List<String> getDatacategories() {

		if(datacategories == null) {
			datacategories = new ArrayList<String>();
		}
		return this.datacategories;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 * 		possible object is
	 *         {@link String }
	 * 
	 */
	public String getName() {

		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 * 
	 */
	public void setName(String value) {

		this.name = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return
	 * 		possible object is
	 *         {@link String }
	 * 
	 */
	public String getDescription() {

		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link String }
	 * 
	 */
	public void setDescription(String value) {

		this.description = value;
	}

	/**
	 * Gets the value of the readonly property.
	 * 
	 * @return
	 * 		possible object is
	 *         {@link Boolean }
	 * 
	 */
	public boolean isReadonly() {

		if(readonly == null) {
			return false;
		} else {
			return readonly;
		}
	}

	/**
	 * Sets the value of the readonly property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link Boolean }
	 * 
	 */
	public void setReadonly(Boolean value) {

		this.readonly = value;
	}
}
